config/routes.rb
Rails.application.routes.draw do
  resources :slide_decks

  root to: 'slide_decks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slide_deck.rb
class SlideDeck < ApplicationRecord
  has_one_attached :presentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/slide_decks_controller.rb
class SlideDecksController < ApplicationController
  before_action :set_slide_deck, only: [:show, :edit, :update, :destroy]

  # GET /slide_decks
  # GET /slide_decks.json
  def index
    @slide_decks = SlideDeck.all
  end

  # GET /slide_decks/1
  # GET /slide_decks/1.json
  def show
  end

  # GET /slide_decks/new
  def new
    @slide_deck = SlideDeck.new
  end

  # GET /slide_decks/1/edit
  def edit
  end

  # POST /slide_decks
  # POST /slide_decks.json
  def create
    @slide_deck = SlideDeck.new(slide_deck_params)

    respond_to do |format|
      if @slide_deck.save
        format.html { redirect_to @slide_deck, notice: 'Slide deck was successfully created.' }
        format.json { render :show, status: :created, location: @slide_deck }
      else
        format.html { render :new }
        format.json { render json: @slide_deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slide_decks/1
  # PATCH/PUT /slide_decks/1.json
  def update
    respond_to do |format|
      if @slide_deck.update(slide_deck_params)
        format.html { redirect_to @slide_deck, notice: 'Slide deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide_deck }
      else
        format.html { render :edit }
        format.json { render json: @slide_deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slide_decks/1
  # DELETE /slide_decks/1.json
  def destroy
    @slide_deck.destroy
    respond_to do |format|
      format.html { redirect_to slide_decks_url, notice: 'Slide deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide_deck
      @slide_deck = SlideDeck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_deck_params
      params.require(:slide_deck).permit(:name, :presentation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slide_decks_helper.rb
module SlideDecksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Previewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slide_decks/_form.html.erb
<%= form_with(model: slide_deck, local: true) do |form| %>
  <% if slide_deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide_deck.errors.count, "error") %> prohibited this slide_deck from being saved:</h2>

      <ul>
      <% slide_deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :presentation %>
    <%= form.file_field :presentation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slide_decks/edit.html.erb
<h1>Editing Slide Deck</h1>

<%= render 'form', slide_deck: @slide_deck %>

<%= link_to 'Show', @slide_deck %> |
<%= link_to 'Back', slide_decks_path %>

app/views/slide_decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slide Decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slide_decks.each do |slide_deck| %>
      <tr>
        <td><%= slide_deck.name %></td>
        <td><%= link_to 'Show', slide_deck %></td>
        <td><%= link_to 'Edit', edit_slide_deck_path(slide_deck) %></td>
        <td><%= link_to 'Destroy', slide_deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide Deck', new_slide_deck_path %>

app/views/slide_decks/new.html.erb
<h1>New Slide Deck</h1>

<%= render 'form', slide_deck: @slide_deck %>

<%= link_to 'Back', slide_decks_path %>

app/views/slide_decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide_deck.name %>
</p>

<p>
  <strong>Preview: </strong>
  <%= image_tag @slide_deck.presentation.preview(resize: "400x400") %>
</p>

<%= link_to 'Edit', edit_slide_deck_path(@slide_deck) %> |
<%= link_to 'Back', slide_decks_path %>